# -*- coding: utf-8 -*-
"""Backtesting v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXjH_sRhAYbMRKtPE-uaVypGkZ7CXoqW
"""

import streamlit as st
import pandas as pd
import ccxt
import backtrader as bt
from datetime import datetime, timezone
import matplotlib

# ИСПРАВЛЕНИЕ 1: Решаем проблему с графиком в серверной среде
matplotlib.use('Agg')

# --- 1. Класс Стратегии для Backtrader (с логикой для фьючерсов) ---
class DcaGridStrategy(bt.Strategy):
    params = (
        # Параметры стратегии
        ('initial_order_size', 100.0),
        ('safety_order_size', 100.0),
        ('price_step_percent', 2.0),
        ('price_step_multiplier', 1.5),
        ('safety_orders_count', 10),
        ('take_profit_percent', 2.0),
        # Параметры фьючерсов
        ('is_futures', False),
        ('leverage', 1),
        ('funding_rate', 0.0001), # Средняя ставка финансирования 0.01%
    )

    def __init__(self):
        self.entry_price = 0
        self.total_cost = 0
        self.total_size = 0
        self.take_profit_price = 0
        self.liquidation_price = 0
        self.safety_orders_placed = 0
        # Таймер для списания funding'а каждые 8 часов
        if self.p.is_futures:
            self.add_timer(
                when=bt.Timer.SESSION_START,
                offset=bt.timedelta(hours=8),
                repeat=bt.timedelta(hours=8)
            )

    def notify_timer(self, timer, when, *args):
        # Списываем комиссию за финансирование
        funding_fee = self.broker.get_value() * self.p.funding_rate
        self.broker.add_cash(-funding_fee)
        self.log(f'FUNDING FEE: -${funding_fee:.2f} charged.')

    def notify_order(self, order):
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(f'BUY EXECUTED: Size {order.executed.size:.4f}, Price: {order.executed.price:.2f}, Cost: {order.executed.value:.2f}')
                self.total_cost += order.executed.value
                self.total_size += order.executed.size
                self.entry_price = self.total_cost / self.total_size
                self.take_profit_price = self.entry_price * (1 + self.p.take_profit_percent / 100)
                # Рассчитываем цену ликвидации (упрощенно)
                if self.p.is_futures:
                    self.liquidation_price = self.entry_price * (1 - (1 / self.p.leverage))
            elif order.issell():
                self.log(f'SELL EXECUTED: Size {order.executed.size:.4f}, Price: {order.executed.price:.2f}, PnL: {order.executed.pnl:.2f}')
                self.reset_cycle()

    def next(self):
        # ИСПРАВЛЕНИЕ 3: Проверка на ликвидацию
        if self.p.is_futures and self.position and self.data.close[0] <= self.liquidation_price:
            self.log(f'!!! LIQUIDATION at Price: {self.data.close[0]:.2f}. Liquidation Price was: {self.liquidation_price:.2f} !!!')
            self.close() # Закрываем позицию по рынку
            self.reset_cycle()
            return

        # Логика повторного входа
        if not self.position:
            self.start_new_cycle()
            return

        # Логика Take Profit
        if self.position and self.data.close[0] >= self.take_profit_price:
            self.sell(size=self.position.size)

        # Логика страховочных ордеров
        if self.safety_orders_placed < self.p.safety_orders_count:
            step = self.p.price_step_percent / 100.0 * (self.p.price_step_multiplier ** self.safety_orders_placed)
            next_safety_price = self.entry_price * (1 - step)
            if self.data.close[0] <= next_safety_price:
                order_size = self.p.safety_order_size / self.data.close[0]
                self.buy(size=order_size)
                self.safety_orders_placed += 1

    def start_new_cycle(self):
        initial_size = self.p.initial_order_size / self.data.close[0]
        self.buy(size=initial_size)
        self.log(f'NEW CYCLE STARTED: Initial Buy @ {self.data.close[0]:.2f}')

    def reset_cycle(self):
        self.total_cost = 0
        self.total_size = 0
        self.safety_orders_placed = 0

    def log(self, txt, dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        log_container.write(f'{dt.isoformat()} - {txt}')

# --- 2. Функция загрузки данных и Пресеты ---
@st.cache_data
def fetch_data(exchange_name, symbol, timeframe, start_date):
    try:
        exchange = getattr(ccxt, exchange_name)()
        since = int(start_date.replace(tzinfo=timezone.utc).timestamp() * 1000)
        all_ohlcv = []
        while True:
            ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since=since, limit=1000)
            if not ohlcv: break
            all_ohlcv.extend(ohlcv)
            since = ohlcv[-1][0] + 1
        df = pd.DataFrame(all_ohlcv, columns=['datetime', 'open', 'high', 'low', 'close', 'volume'])
        df['datetime'] = pd.to_datetime(df['datetime'], unit='ms')
        df.set_index('datetime', inplace=True)
        return df
    except Exception as e:
        st.error(f"Ошибка при загрузке данных: {e}")
        return None

# ИСПРАВЛЕНИЕ 2: Новая структура пресетов
PRESETS = {
    "okx": {
        "Spot": {"BTC/USDT": "BTC-USDT", "ETH/USDT": "ETH-USDT"},
        "Futures": {"BTC/USDT": "BTC-USDT-SWAP", "ETH/USDT": "ETH-USDT-SWAP"}
    },
    "bitmex": {
        "Spot": {}, # У BitMEX нет традиционного спота в CCXT
        "Futures": {"XBT/USDT": "XBTUSDT", "ETH/USDT": "ETHUSDT"}
    }
}

# --- 3. Интерфейс Streamlit ---
st.set_page_config(layout="wide")
st.title("📈 Продвинутый бэктестер для сеточной DCA-стратегии")

with st.sidebar:
    st.header("⚙️ Параметры бэктеста")
    exchange = st.selectbox("Биржа", list(PRESETS.keys()))
    instrument = st.selectbox("Инструмент", list(PRESETS[exchange].keys()))

    available_pairs = list(PRESETS[exchange][instrument].keys())
    if not available_pairs:
        st.warning(f"Для {exchange} ({instrument}) нет готовых пресетов. Введите пару вручную.")
        symbol_display = st.text_input("Торговая пара (тикер CCXT)", "BTC-USDT-SWAP")
    else:
        symbol_display = st.selectbox("Торговая пара", available_pairs)

    symbol_ccxt = PRESETS[exchange][instrument].get(symbol_display, symbol_display)

    timeframe = st.selectbox("Таймфрейм", ['1d', '4h', '1h'])
    start_date = st.date_input("Дата начала", datetime(2023, 1, 1))
    initial_cash = st.number_input("Начальный капитал", value=10000.0)

    st.header("🛠️ Параметры стратегии")
    initial_order_size = st.number_input("Начальный ордер ($)", value=100.0)
    safety_order_size = st.number_input("Страховочный ордер ($)", value=100.0)
    safety_orders_count = st.number_input("Max trigger number", value=10)
    price_step_percent = st.number_input("Grid step (%)", value=2.0)
    price_step_multiplier = st.number_input("Grid step ratio (%)", value=1.5)
    take_profit_percent = st.number_input("Take Profit (%)", value=2.0)

    # Поля только для фьючерсов
    leverage = 1
    funding_rate = 0.0
    is_futures = (instrument == "Futures")
    if is_futures:
        st.header("📈 Параметры фьючерсов")
        leverage = st.slider("Плечо (Leverage)", 1, 100, 10)
        funding_rate = st.number_input("Средняя ставка финансирования (%)", value=0.01, format="%.4f") / 100.0

if st.sidebar.button("🚀 Запустить бэктест"):
    start_datetime = datetime.combine(start_date, datetime.min.time())

    with st.spinner(f"Загружаем данные для {symbol_ccxt} с {exchange}..."):
        data_df = fetch_data(exchange, symbol_ccxt, timeframe, start_datetime)

    if data_df is not None and not data_df.empty:
        st.success("Данные успешно загружены.")
        data_feed = bt.feeds.PandasData(dataname=data_df)

        cerebro = bt.Cerebro()
        cerebro.adddata(data_feed)
        cerebro.addstrategy(DcaGridStrategy,
                            initial_order_size=initial_order_size,
                            safety_order_size=safety_order_size,
                            safety_orders_count=safety_orders_count,
                            price_step_percent=price_step_percent,
                            price_step_multiplier=price_step_multiplier,
                            take_profit_percent=take_profit_percent,
                            is_futures=is_futures,
                            leverage=leverage,
                            funding_rate=funding_rate
                            )

        cerebro.broker.set_cash(initial_cash)
        cerebro.broker.setcommission(commission=0.001, leverage=leverage if is_futures else None)

        st.header("📋 Лог сделок")
        log_container = st.expander("Показать/скрыть лог", expanded=False)

        start_value = cerebro.broker.getvalue()
        cerebro.run()
        end_value = cerebro.broker.getvalue()

        st.header("📊 Результаты")
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Начальный капитал", f"${start_value:,.2f}")
        with col2:
            st.metric("Конечный капитал", f"${end_value:,.2f}", delta=f"${end_value - start_value:,.2f}")

        st.subheader("График")
        fig = cerebro.plot(style='candlestick', barup='green', bardown='red')[0][0]
        st.pyplot(fig)