# -*- coding: utf-8 -*-
"""Backtesting v1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXjH_sRhAYbMRKtPE-uaVypGkZ7CXoqW
"""

import streamlit as st
import pandas as pd
import ccxt
import backtrader as bt
from datetime import datetime, timezone

# --- 1. Класс Стратегии для Backtrader ---
# Логика самого бота остается такой же, как и раньше.
class DcaGridStrategy(bt.Strategy):
    params = (
        ('initial_order_size', 10.0),
        ('safety_order_size', 10.0),
        ('price_step_percent', 1.0),
        ('price_step_multiplier', 1.5),
        ('safety_orders_count', 20),
        ('take_profit_percent', 1.0),
    )

    def __init__(self):
        self.entry_price = 0
        self.total_cost = 0
        self.total_size = 0
        self.take_profit_price = 0
        self.last_safety_price = 0
        self.safety_orders_placed = 0

    def start(self):
        initial_size = self.p.initial_order_size / self.data.close[0]
        self.buy(size=initial_size)
        self.log(f'INITIAL BUY: {initial_size:.4f} @ {self.data.close[0]:.2f}')
        self.last_safety_price = self.data.close[0]

    def notify_order(self, order):
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(f'BUY EXECUTED: Size {order.executed.size:.4f}, Price: {order.executed.price:.2f}, Cost: {order.executed.value:.2f}')
                self.total_cost += order.executed.value
                self.total_size += order.executed.size
                self.entry_price = self.total_cost / self.total_size
                self.take_profit_price = self.entry_price * (1 + self.p.take_profit_percent / 100)
            elif order.issell():
                self.log(f'SELL EXECUTED (TAKE PROFIT): Size {order.executed.size:.4f}, Price: {order.executed.price:.2f}, PnL: {order.executed.pnl:.2f}')
                self.total_cost = 0
                self.total_size = 0
                self.safety_orders_placed = 0

    def next(self):
        if self.position and self.data.close[0] >= self.take_profit_price:
            self.sell(size=self.position.size)
            self.log(f'TAKE PROFIT ORDER PLACED at {self.data.close[0]:.2f}')

        if self.safety_orders_placed < self.p.safety_orders_count:
            step = self.p.price_step_percent / 100.0 * (self.p.price_step_multiplier ** self.safety_orders_placed)
            next_safety_price = self.last_safety_price * (1 - step)
            if self.data.close[0] <= next_safety_price:
                order_size = self.p.safety_order_size / self.data.close[0]
                self.buy(size=order_size)
                self.log(f'SAFETY ORDER PLACED: {self.safety_orders_placed + 1} at {self.data.close[0]:.2f}')
                self.last_safety_price = self.data.close[0]
                self.safety_orders_placed += 1

    def log(self, txt, dt=None):
        dt = dt or self.datas[0].datetime.date(0)
        st.write(f'{dt.isoformat()} - {txt}')

# --- 2. Функция для загрузки данных через CCXT ---
def fetch_data(exchange_name, symbol, timeframe, start_date, end_date):
    try:
        exchange_class = getattr(ccxt, exchange_name)
        exchange = exchange_class()

        start_ts = int(start_date.replace(tzinfo=timezone.utc).timestamp() * 1000)
        end_ts = int(end_date.replace(tzinfo=timezone.utc).timestamp() * 1000)

        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since=start_ts, limit=5000)
        if not ohlcv:
            return None

        df = pd.DataFrame(ohlcv, columns=['datetime', 'open', 'high', 'low', 'close', 'volume'])
        df['datetime'] = pd.to_datetime(df['datetime'], unit='ms')
        df.set_index('datetime', inplace=True)
        return df
    except Exception as e:
        st.error(f"Ошибка при загрузке данных: {e}")
        return None

# --- 3. Интерфейс Streamlit ---
st.set_page_config(layout="wide")
st.title("📈 Бэктестер для сеточной DCA-стратегии на CCXT")

with st.sidebar:
    st.header("⚙️ Параметры бэктеста")
    exchange_name = st.selectbox("Биржа", ['binance', 'bybit', 'okx', 'kucoin', 'gateio'])
    symbol = st.text_input("Торговая пара", "BTC/USDT")
    timeframe = st.selectbox("Таймфрейм", ['1d', '4h', '1h', '30m', '15m', '5m'])
    start_date = st.date_input("Дата начала", datetime(2023, 1, 1))
    end_date = st.date_input("Дата окончания", datetime.now())
    initial_cash = st.number_input("Начальный капитал", value=10000.0)

    st.header("🛠️ Параметры стратегии")
    initial_order_size = st.number_input("Начальный ордер ($)", value=100.0)
    safety_order_size = st.number_input("Страховочный ордер ($)", value=100.0)
    safety_orders_count = st.number_input("Max trigger number", value=10)
    price_step_percent = st.number_input("Grid step (%)", value=2.0)
    price_step_multiplier = st.number_input("Grid step ratio (%)", value=1.5)
    take_profit_percent = st.number_input("Take Profit (%)", value=2.0)

if st.sidebar.button("🚀 Запустить бэктест"):
    with st.spinner(f"Загружаем данные с {exchange_name}..."):
        # Преобразуем даты в datetime объекты для функции
        start_datetime = datetime.combine(start_date, datetime.min.time())
        end_datetime = datetime.combine(end_date, datetime.max.time())

        data_df = fetch_data(exchange_name, symbol, timeframe, start_datetime, end_datetime)

    if data_df is not None and not data_df.empty:
        st.success(f"Данные для {symbol} ({timeframe}) успешно загружены.")
        data_feed = bt.feeds.PandasData(dataname=data_df)

        cerebro = bt.Cerebro()
        cerebro.adddata(data_feed)
        cerebro.addstrategy(DcaGridStrategy,
                            initial_order_size=initial_order_size,
                            safety_order_size=safety_order_size,
                            safety_orders_count=safety_orders_count,
                            price_step_percent=price_step_percent,
                            price_step_multiplier=price_step_multiplier,
                            take_profit_percent=take_profit_percent)

        cerebro.broker.set_cash(initial_cash)

        st.header("📋 Лог сделок")
        start_value = cerebro.broker.getvalue()
        cerebro.run()
        end_value = cerebro.broker.getvalue()

        st.header("📊 Результаты")
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Начальный капитал", f"${start_value:,.2f}")
        with col2:
            st.metric("Конечный капитал", f"${end_value:,.2f}", delta=f"${end_value - start_value:,.2f}")

        st.subheader("График")
        fig = cerebro.plot(style='candlestick', barup='green', bardown='red')[0][0]
        st.pyplot(fig)